<?php

/**
 * Implements hook_field_widget_info().
 */
function classy_paragraphs_field_widget_info() {
  return array(
    'classy_paragraphs_select' => array(
      'label' => t('Classy paragraphs select'),
      'field types' => array('list_text'),
      'behaviors' => array(
        'multiple values' => FIELD_BEHAVIOR_CUSTOM,
      ),
    ),
  );
}

/**
 * Implementation of hook_field_widget_form().
 */
function classy_paragraphs_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  // Abstract over the actual field columns, to allow different field types to
  // reuse those widgets.
  $value_key = key($field['columns']);

  $multiple = $field['cardinality'] > 1 || $field['cardinality'] == FIELD_CARDINALITY_UNLIMITED;
  $required = $element['#required'];
  $has_value = isset($items[0][$value_key]);
  $properties = _options_properties('select', $multiple, $required, $has_value);

  $entity_type = $element['#entity_type'];
  $entity = $element['#entity'];

  // Prepare the list of options.
  $options = classy_paragraphs_get_options($field, $instance);
  // Put current field values in shape.
  $default_value = _options_storage_to_form($items, $options, $value_key, $properties);

  switch ($instance['widget']['type']) {
    case 'classy_paragraphs_select':
      $element += array(
        '#type' => 'select',
        '#default_value' => $default_value,
        // Do not display a 'multiple' select box if there is only one option.
        '#multiple' => $multiple && count($options) > 1,
        '#options' => $options,
      );
      break;
  }

  $element += array(
    '#value_key' => $value_key,
    '#element_validate' => array('options_field_widget_validate'),
    '#properties' => $properties,
  );
  return $element;
}

/**
 * Get list of options from other modules.
 *
 * @param $field
 * @param $instance
 * @return array
 */
function classy_paragraphs_get_options($field, $instance) {
  $options = array();
  $options = module_invoke_all('classy_paragraphs_list_options', $options, $field, $instance);
  drupal_alter('classy_paragraphs_list_options', $options);


  return $options;
}

/**
 * Implements hook_classy_paragraph_list_options().
 */
function classy_paragraphs_classy_paragraphs_list_options($options, $field, $instance) {
  $options['loud'] = t('Loud');
  $options['soft'] = t('Soft');

  return $options;
}
